services:
  video-tools:
    build: ./backend
    container_name: video-editor-tools
    # No volume mounts - videos stay in container only
    environment:
      - PYTHONUNBUFFERED=1
    # Keep container running for video processing
    command: tail -f /dev/null
    restart: unless-stopped