services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8002:8002"
    volumes:
      - ./api:/app
      - ./storage:/app/storage
    restart: unless-stopped

  script-reset:
    image: alpine:latest
    volumes:
      - ./storage:/app/storage
    command: >
      sh -c "
        cp /app/storage/scripts/edit_template.sh /app/storage/scripts/edit.sh &&
        chmod +x /app/storage/scripts/edit.sh &&
        echo 'Script reset completed - edit.sh restored from template'
      "
    restart: "no"

  agent:
    build:
      context: ./agent_worker
      dockerfile: Dockerfile
    env_file:
      - ./agent_worker/agent/.env
    ports:
      - "8000:8000"
    volumes:
      - ./agent_worker:/app
      - ./storage:/app/storage
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - script-reset
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G