services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8002:8002"
    volumes:
      - ./api:/app
      - video_storage:/app/storage/videos
    restart: unless-stopped

  agent:
    build:
      context: ./agent_worker
      dockerfile: Dockerfile
    env_file:
      - ./agent_worker/agent/.env
    ports:
      - "8000:8000"
    volumes:
      - ./agent_worker:/app
      - video_storage:/app/storage/videos
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

volumes:
  video_storage:
    driver: local