services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8002:8002"
    volumes:
      - ./api:/app
      # Map the local storage folder to the container's storage folder
      - ./storage:/app/storage
    restart: unless-stopped

  agent:
    build:
      context: ./agent_worker
      dockerfile: Dockerfile
    env_file:
      - ./agent_worker/agent/.env
    ports:
      - "8000:8000"
    volumes:
      - ./agent_worker:/app
      # Map the local storage folder to the container's storage folder
      - ./storage:/app/storage
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G